/**
 * @patterson/emitter-github-actions — workflows + commit tooling from
 * DevopsDef (E-P6). Contract: contracts/emitter.md — pure, `{ops, gaps}`.
 *
 * Facts honored:
 * - Least-privilege permissions on every workflow (research: default token
 *   scopes are too broad; explicit `permissions:` block always).
 * - setup-bun pinned @v2 — no floating @latest (Constitution IV).
 * - C13: `bun publish` has no OIDC provenance — the release workflow uses a
 *   Node 24 step with `npm publish --provenance`.
 * - S7: `bun pm pack` rewrites workspace:* (verified 2026-07-31); monorepo
 *   changesets release stays gated behind `release.monorepo: "experimental"`.
 * - Workflow files are namespaced `patterson-*.yml` so pre-existing user
 *   workflows (e.g. claude.yml from a PR) are never touched (own-tier on OUR
 *   files only; foreign files stay foreign).
 */
import type { CoverageGap, Emitter, FileOp, FsSnapshot, PattersonProject } from "@patterson/core";

export interface CompileOutput {
  ops: FileOp[];
  gaps: CoverageGap[];
}

const HEADER = "# Generated by patterson (github-actions emitter). Edit patterson.config.ts, then `patterson sync`.\n";

function ciWorkflow(lint: "oxlint" | "biome"): string {
  const lintCmd = lint === "oxlint" ? "bunx oxlint ." : "bunx biome check .";
  return [
    HEADER,
    "name: patterson-ci",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  ci:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "        with:",
    "          bun-version: latest",
    "      - run: bun install --frozen-lockfile",
    "      - run: bunx tsc --noEmit",
    "      - run: bun test",
    `      - run: ${lintCmd}`,
    "",
  ].join("\n");
}

function securityWorkflow(): string {
  return [
    HEADER,
    "name: patterson-security",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  socket:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "        with:",
    "          bun-version: latest",
    "      # Socket supply-chain scan: exits non-zero when the dependency",
    "      # manifests introduce unhealthy packages (needs SOCKET_API_TOKEN).",
    "      - run: bunx socket ci",
    "        env:",
    "          SOCKET_API_TOKEN: ${{ secrets.SOCKET_API_TOKEN }}",
    "",
  ].join("\n");
}

function releaseWorkflow(): string {
  return [
    HEADER,
    "# EXPERIMENTAL (S7): single-package releases only. bun pm pack rewrites",
    "# workspace:* correctly (verified); changesets-driven monorepo releases",
    "# stay opt-in via release.monorepo: \"experimental\".",
    "name: patterson-release",
    "on:",
    "  push:",
    "    tags: [\"v*\"]",
    "",
    "permissions:",
    "  contents: read",
    "  id-token: write   # OIDC for npm provenance (C13)",
    "",
    "jobs:",
    "  publish:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "        with:",
    "          bun-version: latest",
    "      - run: bun install --frozen-lockfile",
    "      - run: bun test",
    "      # C13: bun publish has no OIDC/provenance path — pack with bun,",
    "      # publish the tarball with Node 24 npm for --provenance.",
    "      - run: bun pm pack --destination ./dist",
    "      - uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 24",
    "          registry-url: https://registry.npmjs.org",
    "      - run: npm publish ./dist/*.tgz --provenance --access public",
    "        env:",
    "          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}",
    "",
  ].join("\n");
}

function dependabotConfig(): string {
  return [
    "# Generated by patterson: GitHub Actions updates ONLY (packages go through",
    "# the socket-gated bun flow, not automated bumps).",
    "version: 2",
    "updates:",
    "  - package-ecosystem: github-actions",
    "    directory: /",
    "    schedule:",
    "      interval: weekly",
    "",
  ].join("\n");
}

function lefthookConfig(lint: "oxlint" | "biome", conventional: boolean): string {
  const lintCmd = lint === "oxlint" ? "bunx oxlint ." : "bunx biome check .";
  return [
    "# Generated by patterson. `bunx lefthook install` once per clone.",
    "pre-commit:",
    "  parallel: true",
    "  jobs:",
    "    - name: lint",
    `      run: ${lintCmd}`,
    "    - name: typecheck",
    "      run: bunx tsc --noEmit",
    ...(conventional
      ? [
          "commit-msg:",
          "  jobs:",
          "    - name: commitlint",
          "      run: bunx commitlint --edit {1}",
        ]
      : []),
    "",
  ].join("\n");
}

/** Full compile: FileOps plus CoverageGaps. */
export function compileGithubActions(ir: PattersonProject, _snapshot: FsSnapshot): CompileOutput {
  const ops: FileOp[] = [];
  const gaps: CoverageGap[] = [];
  if (!ir.targets.includes("github-actions")) return { ops, gaps };

  const devops = ir.devops;
  if (devops === undefined) {
    gaps.push({
      fallbackApplied: true,
      entityId: "devops",
      targetId: "github-actions",
      reason: "github-actions is targeted but `devops` is not configured — nothing to emit.",
    });
    return { ops, gaps };
  }

  for (const workflow of devops.workflows) {
    if (workflow === "ci") {
      ops.push({
        path: ".github/workflows/patterson-ci.yml",
        format: "yaml",
        mode: "own",
        content: ciWorkflow(devops.lint),
      });
    } else if (workflow === "security") {
      ops.push({
        path: ".github/workflows/patterson-security.yml",
        format: "yaml",
        mode: "own",
        content: securityWorkflow(),
      });
      ops.push({
        path: "github-actions/socket-token",
        format: "markdown",
        mode: "instruct",
        content:
          "The patterson-security workflow needs a `SOCKET_API_TOKEN` repository secret " +
          "(GitHub → Settings → Secrets and variables → Actions).",
      });
    } else {
      ops.push({
        path: ".github/workflows/patterson-release.yml",
        format: "yaml",
        mode: "own",
        content: releaseWorkflow(),
      });
      ops.push({
        path: "github-actions/npm-token",
        format: "markdown",
        mode: "instruct",
        content:
          "The patterson-release workflow needs an `NPM_TOKEN` repository secret with publish " +
          "rights (or configure an npm Trusted Publisher for tokenless OIDC and drop the token).",
      });
      if (devops.release?.monorepo !== "experimental") {
        gaps.push({
          fallbackApplied: true,
          entityId: "devops.release",
          targetId: "github-actions",
          reason:
            "Release workflow covers a single package. Monorepo (changesets) releases are " +
            'S7-gated: opt in with devops.release.monorepo: "experimental".',
        });
      }
    }
  }

  if (devops.commit?.lefthook === true) {
    ops.push({
      path: "lefthook.yml",
      format: "yaml",
      mode: "own",
      content: lefthookConfig(devops.lint, devops.commit.conventional),
    });
  }
  if (devops.commit?.conventional === true) {
    ops.push({
      path: "commitlint.config.js",
      format: "text",
      mode: "own",
      content: 'export default { extends: ["@commitlint/config-conventional"] };\n',
    });
  }

  if (devops.depUpdates === "dependabot-actions-only") {
    ops.push({
      path: ".github/dependabot.yml",
      format: "yaml",
      mode: "own",
      content: dependabotConfig(),
    });
  } else if (devops.depUpdates === "renovate") {
    ops.push({
      path: "renovate.json",
      format: "json",
      mode: "own",
      content: `${JSON.stringify(
        {
          $schema: "https://docs.renovatebot.com/renovate-schema.json",
          extends: ["config:recommended"],
          rangeStrategy: "pin",
        },
        null,
        2,
      )}\n`,
    });
  }

  return { ops, gaps };
}

/** Core-contract emitter (gaps available via compileGithubActions). */
export const githubActionsEmitter: Emitter = {
  targets: ["github-actions"],
  compile(ir, snapshot) {
    return compileGithubActions(ir, snapshot).ops;
  },
};

export function snapshotPaths(_ir: PattersonProject): string[] {
  return [
    ".github/workflows/patterson-ci.yml",
    ".github/workflows/patterson-security.yml",
    ".github/workflows/patterson-release.yml",
    ".github/dependabot.yml",
    "lefthook.yml",
    "commitlint.config.js",
    "renovate.json",
  ];
}

export function coverageGaps(ir: PattersonProject, snapshot: FsSnapshot): CoverageGap[] {
  return compileGithubActions(ir, snapshot).gaps;
}
